rss_key = 'dig-music-rss-cache'
cate_key = 'dig-music-category-cache'
tagcloud_key = 'dig-music-tagcolud-cache'
tags_key = 'dig-music-tags-cache'
links_key = 'dig-music-links-cache'
ads_key = 'dig-music-ads-cache'
article_key = 'dig-music-single-article-cache'
article_related_key = 'dig-music-art-rel-cache'